import fs from 'node:fs';
import path from 'node:path';
import { listTasks, readyQueue, lastNext, isOpen } from './tasks.mjs';
import { projectName, focusList } from './plan.mjs';

export const COLUMNS = [
  ['todo', 'Todo'],
  ['ready', 'Ready'],
  ['in_progress', 'In progress'],
  ['waiting', 'Waiting'],
  ['done', 'Done'],
];
const DONE_MAX = 5;

// An epic with no open task is closed: its cards collapse into one archive line.
// Tasks without an epic are never archived, so a board without epics renders as before.
export function archived(tasks) {
  const live = new Set(tasks.filter(isOpen).map((t) => t.data.epic));
  const out = new Map();
  for (const t of tasks) {
    if (!t.data.epic || live.has(t.data.epic) || t.data.status === 'dropped') continue;
    const a = out.get(t.data.epic) ?? { n: 0, updated: '' };
    out.set(t.data.epic, { n: a.n + 1, updated: t.data.updated > a.updated ? t.data.updated : a.updated });
  }
  return out;
}

// `ready` is computed over every task: a hidden (archived) done task is still a satisfied dependency.
export function columns(tasks, arch = new Map()) {
  const ready = new Set(readyQueue(tasks).map((t) => t.id));
  const cols = Object.fromEntries(COLUMNS.map(([k]) => [k, []]));
  for (const t of tasks) {
    if (arch.has(t.data.epic)) continue;
    const s = t.data.status;
    if (s === 'todo') cols[ready.has(t.id) ? 'ready' : 'todo'].push(t);
    else if (s !== 'dropped' && cols[s]) cols[s].push(t);
  }
  return cols;
}

// On a board with epics, Done is capped in the view only (highest order = latest stages); the heading keeps the full count.
const shown = (cols, k, cap) => (cap && k === 'done' ? cols.done.slice(-DONE_MAX) : cols[k]);
const count = (cols, k, list) => `${cols[k].length}${list.length < cols[k].length ? `, ${list.length} shown` : ''}`;
const archiveLine = (e, a) => `${e} · ${a.n} done${a.updated ? ` · ${a.updated}` : ''}`;

const nextOf = (t) => (t.data.status === 'done' ? null : lastNext(t));

function cardLine(t) {
  const bits = [`**${t.id}** ${t.data.title}`];
  if (t.data.epic) bits.push(t.data.epic);
  if (t.data.milestone) bits.push(t.data.milestone);
  if (t.data.depends_on.length) bits.push(`after ${t.data.depends_on.join(', ')}`);
  if (t.data.worktrees.length) bits.push(`@ ${t.data.worktrees.join(', ')}`);
  if (t.data.waiting_on) bits.push(`waiting: ${t.data.waiting_on}`);
  const next = nextOf(t);
  if (next) bits.push(`next: ${next.next}`);
  return `- ${bits.join(' · ')}`;
}

export function renderBoardMd(pm, tasks = listTasks(pm)) {
  const arch = archived(tasks);
  const cols = columns(tasks, arch);
  const keys = new Set(tasks.map((t) => t.data.epic).filter(Boolean));
  const out = [`# Board — ${projectName(pm)}`, '', `Focus: ${focusList(pm, keys).join(' · ') || '—'}`, '', '<!-- generated by pm; do not edit -->'];
  for (const [k, label] of COLUMNS) {
    const list = shown(cols, k, keys.size);
    out.push('', `## ${label} (${count(cols, k, list)})`, ...list.map(cardLine));
  }
  if (arch.size) out.push('', '## Archive', ...[...arch].map(([e, a]) => `- ${archiveLine(e, a)}`));
  return `${out.join('\n')}\n`;
}

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);

function card(t) {
  const next = nextOf(t);
  const meta = [
    t.data.epic && `<span class="tag">${esc(t.data.epic)}</span>`,
    t.data.milestone && `<span class="tag">${esc(t.data.milestone)}</span>`,
    t.data.depends_on.length && `<span>after ${esc(t.data.depends_on.join(', '))}</span>`,
    t.data.worktrees.length && `<span>@ ${esc(t.data.worktrees.join(', '))}</span>`,
  ].filter(Boolean).join(' ');
  return `<article class="card"><b>${esc(t.id)}</b> ${esc(t.data.title)}`
    + (meta ? `<div class="meta">${meta}</div>` : '')
    + (t.data.waiting_on ? `<div class="wait">waiting: ${esc(t.data.waiting_on)}</div>` : '')
    + (next ? `<div class="next">next: ${esc(next.next)}</div>` : '')
    + '</article>';
}

export function renderBoardHtml(pm, tasks = listTasks(pm)) {
  const arch = archived(tasks);
  const cols = columns(tasks, arch);
  const keys = new Set(tasks.map((t) => t.data.epic).filter(Boolean));
  const name = esc(projectName(pm));
  const sections = COLUMNS.map(([k, label]) => {
    const list = shown(cols, k, keys.size);
    return `<section class="col"><h2>${label} · ${count(cols, k, list)}</h2>${list.map(card).join('')}</section>`;
  }).join('');
  const archive = arch.size
    ? `<details class="archive" style="margin-top:16px;color:var(--muted)"><summary>Archive · ${arch.size}</summary>${[...arch].map(([e, a]) => `<div>${esc(archiveLine(e, a))}</div>`).join('')}</details>`
    : '';
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="10">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${name} · board</title>
<style>
:root{--bg:#f6f6f4;--col:#ecebe7;--card:#fff;--fg:#1d1d1b;--muted:#6b6a65;--line:#d9d8d2;--accent:#3a5bd9;--warn:#a25400}
@media (prefers-color-scheme:dark){:root{--bg:#161614;--col:#1f1f1c;--card:#2a2a26;--fg:#ecebe7;--muted:#a3a29b;--line:#3a3a35;--accent:#8ea5ff;--warn:#f0a35e}}
*{box-sizing:border-box}body{margin:0;padding:16px;background:var(--bg);color:var(--fg);font:14px/1.4 system-ui,sans-serif}
h1{font-size:18px;margin:0 0 4px}.focus{color:var(--muted);margin:0 0 16px}
.board{display:grid;grid-template-columns:repeat(5,minmax(200px,1fr));gap:12px;overflow-x:auto}
.col{background:var(--col);border-radius:8px;padding:8px}
.col h2{font-size:12px;margin:4px 4px 8px;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}
.card{background:var(--card);border:1px solid var(--line);border-radius:6px;padding:8px;margin-bottom:8px}
.meta,.next,.wait{font-size:12px;color:var(--muted);margin-top:4px}.tag{color:var(--accent)}.wait{color:var(--warn)}
</style></head><body>
<h1>${name}</h1><p class="focus">Focus: ${esc(focusList(pm, keys).join(' · ') || '—')}</p>
<main class="board">${sections}</main>${archive}
</body></html>
`;
}

// One directory scan for both views; callers that already hold the tasks pass them in.
export function writeBoard(pm, tasks = listTasks(pm)) {
  fs.writeFileSync(path.join(pm, 'BOARD.md'), renderBoardMd(pm, tasks));
  fs.writeFileSync(path.join(pm, 'board.html'), renderBoardHtml(pm, tasks));
}
